name: Run tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable

    - name: Install SDL2
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev

    - name: Build VM
      run: cargo build

    - name: Release build
      run: cargo build --release

    - name: Test VM
      run: RUST_BACKTRACE=1 cargo test

    - name: Test plush command-line arguments
      working-directory: .
      run: |
        cargo run tests/empty.psh
        cargo run tests/fact.psh
        cargo run -- --no-exec examples/raytracer.psh
        cargo run -- --eval ''
        cargo run -- --eval '$println(1);'
        cargo run examples/command_args.psh
        cargo run examples/command_args.psh foo bar

    # We do this to verify that the benchmarks can all run without crashing
    # The benchmarks are designed to run fairly quickly, less than 5 seconds each
    - name: Run benchmarks
      run: ./run_benchmarks.sh
